export default {
  PRODUCTS_LOADING_ALL: "@products/PRODUCTS_LOADING_ALL",
  PRODUCTS_LOADING_ALL_ERROR: "@products/PRODUCTS_LOADING_ALL_ERROR",
  PRODUCTS_RECIVIED: "@products/PRODUCTS_RECIVED",
  PRODUCT_RECIVED_END: "@products/PRODUCTS_RECIVED_END",
  PRODUCTS_FILTER_START: "@products/PRODUCTS_FILTER_START",
  PRODUCTS_FILTER_END: "@products/PRODUCTS_FILTER_END",
  PRODUCTS_SET_CATEGORIES_LIST: "@products/PRODUCTS_SET_CATEGORIES_LIST",
  SET_ACTIVE_SECTION: "@products/SET_ACTIVE_SECTION"
};
