export default {
  CART_ADD_TO_CART: "@cart/CART_ADD_TO_CART",
  CART_DELETE_FROM_CART: "@cart/CART_DELETE_FROM_CART",
  CART_DELETE_ONE_FROM_CART: "@cart/DELETE_ONE_FROM_CART",
  CART_ADD_ONE_TO_CART: "@cart/ADD_ONE_TO_CART"
};
